-- ------------------------------------------------
-- HR.DEPARTMENTS (部門マスター)
-- ------------------------------------------------
MERGE INTO HR.DEPARTMENTS T
USING (
    SELECT
        'OF0001' AS DEPT_ID, '東京本社' AS DEPT_NAME, NULL AS PARENT_DEPT_ID, TO_DATE('2022-04-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT,
        'system' AS CREATED_BY, TO_DATE('2026-04-01 10:15:00', 'YYYY-MM-DD HH24:MI:SS') AS UPDATED_AT, 'sys_administrator' AS UPDATED_BY
    FROM dual
) S
ON (
    T.DEPT_ID = S.DEPT_ID
)
WHEN MATCHED THEN
    UPDATE SET
        T.DEPT_NAME = S.DEPT_NAME,
        T.PARENT_DEPT_ID = S.PARENT_DEPT_ID,
        T.CREATED_AT = S.CREATED_AT,
        T.CREATED_BY = S.CREATED_BY,
        T.UPDATED_AT = S.UPDATED_AT,
        T.UPDATED_BY = S.UPDATED_BY
WHEN NOT MATCHED THEN
    INSERT (
        DEPT_ID, DEPT_NAME, PARENT_DEPT_ID, CREATED_AT,
        CREATED_BY, UPDATED_AT, UPDATED_BY
    )
    VALUES (
        S.DEPT_ID, S.DEPT_NAME, S.PARENT_DEPT_ID, S.CREATED_AT,
        S.CREATED_BY, S.UPDATED_AT, S.UPDATED_BY
    );

MERGE INTO HR.DEPARTMENTS T
USING (
    SELECT
        'OF0002' AS DEPT_ID, '横浜営業所' AS DEPT_NAME, NULL AS PARENT_DEPT_ID, TO_DATE('2023-01-10 09:30:00', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT,
        'sys_administrator' AS CREATED_BY, TO_DATE('2026-01-15 11:20:00', 'YYYY-MM-DD HH24:MI:SS') AS UPDATED_AT, 'sys_operator' AS UPDATED_BY
    FROM dual
) S
ON (
    T.DEPT_ID = S.DEPT_ID
)
WHEN MATCHED THEN
    UPDATE SET
        T.DEPT_NAME = S.DEPT_NAME,
        T.PARENT_DEPT_ID = S.PARENT_DEPT_ID,
        T.CREATED_AT = S.CREATED_AT,
        T.CREATED_BY = S.CREATED_BY,
        T.UPDATED_AT = S.UPDATED_AT,
        T.UPDATED_BY = S.UPDATED_BY
WHEN NOT MATCHED THEN
    INSERT (
        DEPT_ID, DEPT_NAME, PARENT_DEPT_ID, CREATED_AT,
        CREATED_BY, UPDATED_AT, UPDATED_BY
    )
    VALUES (
        S.DEPT_ID, S.DEPT_NAME, S.PARENT_DEPT_ID, S.CREATED_AT,
        S.CREATED_BY, S.UPDATED_AT, S.UPDATED_BY
    );

MERGE INTO HR.DEPARTMENTS T
USING (
    SELECT
        'OF0003' AS DEPT_ID, '大宮営業所' AS DEPT_NAME, NULL AS PARENT_DEPT_ID, TO_DATE('2023-06-05 10:00:00', 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT,
        'system' AS CREATED_BY, TO_DATE('2026-02-18 14:05:00', 'YYYY-MM-DD HH24:MI:SS') AS UPDATED_AT, 'sys_operator' AS UPDATED_BY
    FROM dual
) S
ON (
    T.DEPT_ID = S.DEPT_ID
)
WHEN MATCHED THEN
    UPDATE SET
        T.DEPT_NAME = S.DEPT_NAME,
        T.PARENT_DEPT_ID = S.PARENT_DEPT_ID,
        T.CREATED_AT = S.CREATED_AT,
        T.CREATED_BY = S.CREATED_BY,
        T.UPDATED_AT = S.UPDATED_AT,
        T.UPDATED_BY = S.UPDATED_BY
WHEN NOT MATCHED THEN
    INSERT (
        DEPT_ID, DEPT_NAME, PARENT_DEPT_ID, CREATED_AT,
        CREATED_BY, UPDATED_AT, UPDATED_BY
    )
    VALUES (
        S.DEPT_ID, S.DEPT_NAME, S.PARENT_DEPT_ID, S.CREATED_AT,
        S.CREATED_BY, S.UPDATED_AT, S.UPDATED_BY
    );

